spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 1000
              time: 60
              unit: seconds
    - cache-name: buckets
      url: /widgets
      rate-limits:
        - bandwidths:
            - capacity: 200
              time: 60
              unit: seconds
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env,metrics,logfile,info
  server:
    port: 8081
logging:
  file:
    name: ./logs/widget-api.log
info:
  app:
    name: Widget Api
    description: Solution for technical assignment by Sanket Gujarathi
---
spring:
  profiles: sql
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
    initialization-mode: embedded
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,
      org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration,
      org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,
      org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: nosql
  data:
    mongodb:
      user: test
      password:
      uri: mongodb://localhost:51531/db
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration